# Generated by Django 3.2.7 on 2021-09-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0003_watcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_field', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('previous_value', models.CharField(max_length=20)),
                ('new_value', models.CharField(max_length=20)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing_system.issue')),
            ],
        ),
    ]
