# Generated by Django 3.2.7 on 2021-09-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0006_alter_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(null=True, to='ticketing_system.Labels'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pm', 'Project Manager'), ('standard', 'Standard')], default='admin', max_length=15),
        ),
    ]
