# Generated by Django 3.2.7 on 2021-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0007_auto_20210917_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='ticketing_system.Labels'),
        ),
    ]
