# Generated by Django 3.2.7 on 2021-09-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing_system', '0009_auto_20210917_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('work_description', models.TextField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing_system.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logging_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
