# Generated by Django 3.2.7 on 2021-09-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0010_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timelog',
            name='time_taken',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
